#!/usr/bin/env python3
"""Regenerate apps/tensaco/src/data/team.ts from team/*/profile.yml (public fields only).

    python3 team/sync.py
"""
import glob, json, os, yaml

here = os.path.dirname(os.path.abspath(__file__))
out = os.path.join(here, '..', 'apps', 'tensaco', 'src', 'data', 'team.ts')
people = []
for f in glob.glob(os.path.join(here, '*', 'profile.yml')):
    p = yaml.safe_load(open(f))
    pub = p.get('public') or {}
    if not pub.get('show_on_site'):
        continue
    people.append({
        'order': pub['order'], 'slug': p['slug'], 'name': p['name'], 'kind': p['kind'],
        'title': p['title'], 'shortTitle': p.get('short_title', p['title']), 'department': p['department'],
        'location': p['location'], 'reportsTo': p.get('reports_to'), 'photo': f"/media/people/{p['slug']}.jpg",
        'pronouns': p.get('pronouns'), 'email': p['email'], 'card': pub['card_line'], 'bio': pub['bio'],
        'longBio': pub.get('long_bio') or [pub['bio']], 'workingStyle': pub.get('working_style'),
        'responsibilities': p.get('responsibilities') or [], 'elsewhere': pub.get('elsewhere'),
        'links': pub.get('links') or [],
    })
people.sort(key=lambda x: x['order'])
for x in people: del x['order']
body = ',\n'.join('  ' + json.dumps(x, ensure_ascii=False) for x in people)
open(out, 'w').write(f"""/**
 * TensaCo's team. GENERATED by team/sync.py from team/<slug>/profile.yml; edit the YAML, then rerun the script.
 * kind 'ai-agent' people are autonomous agents and carry the "AI agent" badge wherever they are shown.
 */
export type Person = {{
  slug: string; name: string; kind: 'human' | 'ai-agent'; title: string; shortTitle: string; department: string
  location: string; reportsTo: string | null; photo: string; pronouns: string | null; email: string; card: string
  bio: string; longBio: string[]; workingStyle: string | null; responsibilities: string[]; elsewhere: string | null
  links: {{ label: string; url: string }}[]
}}

export const TEAM: Person[] = [
{body},
]

export const CEO = TEAM.find((p) => p.title === 'Chief Executive Officer')!
export const HUMANS = TEAM.filter((p) => p.kind === 'human')
export const AGENTS = TEAM.filter((p) => p.kind === 'ai-agent')
export const personBySlug = (slug: string | null) => TEAM.find((p) => p.slug === slug)
export const reportsOf = (slug: string) => TEAM.filter((p) => p.reportsTo === slug)
export const firstName = (p: Person) => p.name.split(' ')[0]
""")
print(f'wrote {len(people)} people to {os.path.relpath(out)}')
