// Writes apps/account/.dev.vars and apps/tensaco/.dev.vars (gitignored) for `wrangler dev` from .env.local.
//   npm run env:dev
// Locally the session cookie is host-only (COOKIE_DOMAIN empty) and staff notifications go to Resend's test inbox
// unless STAFF_EMAIL is set in .env.local.
import { readFileSync, writeFileSync } from 'node:fs'

const root = new URL('..', import.meta.url)
const env = Object.fromEntries(
  readFileSync(new URL('.env.local', root), 'utf8').split('\n')
    .map((l) => /^\s*([A-Z_][A-Z0-9_]*)\s*=\s*(.*)\s*$/.exec(l))
    .filter(Boolean)
    .map(([, k, v]) => [k, v.replace(/^"(.*)"$/, '$1')]),
)
const vars = {
  RESEND_API_KEY: env.RESEND_API_KEY ?? '',
  EMAIL_FROM: env.EMAIL_FROM ?? 'TensaCo <no-reply@tensaco.ai>',
  EMAIL_REPLY_TO: env.EMAIL_REPLY_TO ?? 'hello@tensaco.ai',
  STAFF_EMAIL: env.STAFF_EMAIL ?? 'delivered+staff@resend.dev',
  ACCOUNT_URL: env.ACCOUNT_URL ?? 'http://localhost:8788',
  SITE_URL: env.SITE_URL ?? 'http://localhost:8787',
  COOKIE_DOMAIN: '',
}
const body = '# Generated by scripts/dev-vars.mjs from .env.local. Do not commit.\n'
  + Object.entries(vars).map(([k, v]) => `${k}=${JSON.stringify(v)}`).join('\n') + '\n'
for (const app of ['account', 'tensaco']) {
  writeFileSync(new URL(`apps/${app}/.dev.vars`, root), body, { mode: 0o600 })
  console.log(`wrote apps/${app}/.dev.vars`)
}
